xcopy src\index.html compiled /s /i /d /y
xcopy src\web.config compiled /s /i /d /y
emcc -o compiled/callisto.html^
 src/Callisto.cpp^
 ../Engine/AI/Ticker.cpp^
 ../Engine/Assets/ActorAsset.cpp^
 ../Engine/Assets/MapAsset.cpp^
 ../Engine/Assets/MaterialAsset.cpp^
 ../Engine/Assets/PVSAsset.cpp^
 ../Engine/Assets/SpriteSheetAsset.cpp^
 ../Engine/Assets/StaticMeshAsset.cpp^
 ../Engine/Assets/TextAsset.cpp^
 ../Engine/Assets/TextureAsset.cpp^
 ../Engine/Assets/WorldMeshAsset.cpp^
 ../Engine/Core/Actor.cpp^
 ../Engine/Core/ActorControllerManager.cpp^
 ../Engine/Core/ActorInstance.cpp^
 ../Engine/Core/AssetManager.cpp^
 ../Engine/Core/CollisionMesh.cpp^
 ../Engine/Core/DebugVisualisationRenderer.cpp^
 ../Engine/Core/Engine.cpp^
 ../Engine/Core/EngineBehaviour.cpp^
 ../Engine/Core/Factory.cpp^
 ../Engine/Core/FrameTimer.cpp^
 ../Engine/Core/Renderer.cpp^
 ../Engine/Core/SceneManager.cpp^
 ../Engine/Core/SubActor.cpp^
 ../Engine/Core/UnitTester.cpp^
 ../Engine/Core/Volume.cpp^
 ../Engine/Core/VolumeManager.cpp^
 ../Engine/FileIO/TokenFileParser.cpp^
 ../Engine/FileIO/WebBrowserFileLoader.cpp^
 ../Engine/Input/AggregatedGamePad.cpp^
 ../Engine/Input/KeyboardMouseGamePad.cpp^
 ../Engine/Input/NullPhysicalGamePad.cpp^
 ../Engine/Input/TouchScreenGamePad.cpp^
 ../Engine/Input/WebBrowserKeyboard.cpp^
 ../Engine/Input/WebBrowserMouse.cpp^
 ../Engine/Input/WebBrowserPhysicalGamePad.cpp^
 ../Engine/Input/WebBrowserTouchScreen.cpp^
 ../Engine/Json/JsonParser.cpp^
 ../Engine/Json/JsonProperty.cpp^
 ../Engine/Json/JsonValue.cpp^
 ../Engine/Logging/WebBrowserLogger.cpp^
 ../Engine/Math/CollisionFace.cpp^
 ../Engine/Math/CollisionLine.cpp^
 ../Engine/Math/AABB.cpp^
 ../Engine/Math/CollisionFace.cpp^
 ../Engine/Math/CollisionLine.cpp^
 ../Engine/Math/Mat2.cpp^
 ../Engine/Math/Mat4.cpp^
 ../Engine/Math/Math.cpp^
 ../Engine/Math/Plane.cpp^
 ../Engine/Math/Ray3.cpp^
 ../Engine/Math/Sphere.cpp^
 ../Engine/Math/Vec3.cpp^
 ../Engine/Rasterization/OpenGL/OpenGLHelper.cpp^
 ../Engine/Rasterization/OpenGL/OpenGLRasterizer.cpp^
 ../Engine/Rasterization/RasterJobManager.cpp^
 ../Engine/Threading/WebBrowserThreadManager.cpp^
 ../Engine/Threading/Worker.cpp^
 ../Engine/Time/WebBrowserTimestampProvider.cpp^
 ../Engine/util/StringUtil.cpp^
 ../Game/ActorControllers/CharacterActorController.cpp^
 ../Game/ActorControllers/DoorActorController.cpp^
 ../Game/ActorControllers/FirstPersonPlayerActorController.cpp^
 ../Game/ActorControllers/KeyActorController.cpp^
 ../Game/ActorControllers/MapTransitionActorController.cpp^
 ../Game/ActorControllers/ProjectileActorController.cpp^
 ../Game/ActorControllers/SpawnPointActorController.cpp^
 ../Game/ActorControllers/SpawnTriggerActorController.cpp^
 ../Game/Game.cpp^
 ../Game/GameController.cpp^
 --js-library src/CallistoLib.js -I"../Engine" -I"../Game"